# Generated by Django 5.2.3 on 2025-06-26 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='unique_id',
            field=models.CharField(default='TEMPID', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sale',
            name='shop',
            field=models.ForeignKey(db_column='shop_unique_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.shop', to_field='unique_id'),
        ),
    ]
