# Generated by Django 5.2.3 on 2025-07-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditlog',
            name='mode_of_payment',
            field=models.CharField(choices=[('GPay', 'GPay'), ('Cash', 'Cash')], default='Cash', max_length=10),
        ),
    ]
