# Generated by Django 5.2.3 on 2025-06-26 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_shop_unique_id_alter_sale_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.shop'),
        ),
    ]
